server:
  port: 9990
mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: cn.eblcu.sso.mapper
  type-handlers-package: org.apache.ibatis.type.LocalDateTypeHandler
redis:
  hostName: 127.0.0.1
  port: 6379
  password: 1234567
  #超时时间
  timeout: 10000
  #最大空闲数
  maxIdle: 300
  #连接池最大连接数
  maxTotal: 1000
  #最大建立连接等待时间。如果超过此时间将接到异常。
  maxWaitMillis: 1000
  #连接的最小空闲时间 默认1800000毫秒(30分钟)
  minEvictableIdleTimeMillis: 300000
  #每次释放连接的最大数目,默认3
  numTestsPerEvictionRun: 10
  #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1
  timeBetweenEvictionRunsMillis: 30000
  #是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
  testOnBorrow: true
  #在空闲时检查有效性, 默认false
  testWhileIdle: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mytest?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  servlet:
    multipart:
      #是否支持批量上传
      enabled: true
      #上传文件最大为 20M
      max-file-size: 20MB
      #上传总数据大小 200M
      max-request-size: 200MB
#    type: com.zaxxer.hikari.HikariDataSource
token:
  # token 失效时间 20分钟
  expires: 1200
#控制swagger启用或是禁用
swagger:
  enable: true
email:
  #发送人邮箱
  fromMailAddress: jiaodongdong@blcu.edu.cn
  #发送邮箱授权码
  fromMailPassword: WSFAAaq6fC6uSHft
  #发送人的昵称显示
  name: 北语客服
  #邮件的标题
  mailTitle: 北语注册验证
  #验证码有效时间
  outTime: 120

#用户头像地址
file:
  imagePath: E:/userPhotos/
#本机域名配置
localUrl: http://192.168.0.178:9990