server:
  port: 9990
mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: cn.eblcu.sso.mapper
  type-handlers-package: org.apache.ibatis.type.LocalDateTypeHandler

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mytest?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
#    type: com.zaxxer.hikari.HikariDataSource
